// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzBKjbXWac7-DRUoey1Li76-LsfcmEgc',
    appId: '1:900783377436:web:244703c75c75e90d2d63d9',
    messagingSenderId: '900783377436',
    projectId: 'flutter-final-bd170',
    authDomain: 'flutter-final-bd170.firebaseapp.com',
    storageBucket: 'flutter-final-bd170.appspot.com',
    measurementId: 'G-2YRDQHFNYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOg6wIdp-GAENOSUivuda1gpv3pTMfUEA',
    appId: '1:900783377436:android:d62d6ab0e49255442d63d9',
    messagingSenderId: '900783377436',
    projectId: 'flutter-final-bd170',
    storageBucket: 'flutter-final-bd170.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5l354KtYFm4a1vfR4G2qxUZdayTLEKnI',
    appId: '1:900783377436:ios:b306ea875a44d3742d63d9',
    messagingSenderId: '900783377436',
    projectId: 'flutter-final-bd170',
    storageBucket: 'flutter-final-bd170.appspot.com',
    iosBundleId: 'com.example.flutterFinalExam',
  );
}
